package com.boss.testoverwatchherocompanion;

import java.util.ArrayList;
import java.util.List;

public class HeroManager
{
    public static List<Hero> getAllHeroes()
    {
        List<Hero> heroes = new ArrayList<>();

        Hero ana = new Hero();
        ana.heroName = "Ana";
        ana.heroDifficulty = 3;
        ana.heroStrengths = "Long ranged healing";
        ana.heroWeaknesses = "Low damage";
        ana.heroHealth = 200;
        ana.heroArmor = 0;
        ana.heroShield = 0;
        ana.heroLeftClickDamage = "Ana’s rifle shoots darts that can restore 75 health to her allies or deal 70 damage to her enemies. 1.25 shots per second. 14 rounds. 1.5 second reload. 90 m/s projectile. Can't headshot.";
        ana.heroRightClickDamage = "Ana zooms in taking 0.25 seconds and zooming out in 0.15 seconds. Shots are hitscan. 1.9 m/s movement speed. Can't headshot.";
        ana.heroSpeed = "5.5 meters per second";
        ana.heroPassiveName = "None";
        ana.heroPassive = "";
        ana.heroAbility1Name = "Sleep Dart";
        ana.heroAbility1 = "Ana fires a dart dealing 5 damage, rendering an enemy unconscious for 6 seconds or until they take damage. 0.5 second cast. 12 second cooldown.";
        ana.heroAbility2Name = "Biotic Grenade";
        ana.heroAbility2 = "Ana throws a grenade dealing 60 damage to enemies and healing 100 health to allies in a 4 meter area of effect. Affected allies will receive 50% increased healing and enemies have healing disabled for 4 seconds. 10 second cooldown.";
        ana.heroUltimateName = "Nano Boost";
        ana.heroUltimate = "Ana hits one of her allies within 40 meters with a combat boost. They recover 250 health, move 30% faster, deal 50% more damage, and take 50% less damage for 8 seconds. 0.15 second cast.";
        ana.heroTipsAndTricks = "Stay in the back to heal your allies and shoot enemies. Interrupt enemy ultimates with Sleep Dart.";
        ana.heroClass = "support";
        ana.heroImage = R.drawable.ana_smallerportrait;
        heroes.add(ana);

        Hero ashe = new Hero();
        ashe.heroName = "Ashe";
        ashe.heroDifficulty = 2;
        ashe.heroStrengths = "High damage";
        ashe.heroWeaknesses = "Low mobility";
        ashe.heroHealth = 200;
        ashe.heroArmor = 0;
        ashe.heroShield = 0;
        ashe.heroLeftClickDamage = "Ashe's semi-automatic rifle fires 4 shots per second dealing 40 damage per shot. 12 rounds. 20 meter falloff for 50% damage. 0.5 seconds initial plus 0.3 seconds reload per bullet.";
        ashe.heroRightClickDamage = "Ashe aims down sights and shoots dealing 85 damage. 1.42 shots per second. 30 meter falloff.";
        ashe.heroSpeed = "5.5 meters per second";
        ashe.heroPassiveName = "None";
        ashe.heroPassive = "";
        ashe.heroAbility1Name = "Dynamite";
        ashe.heroAbility1 = "Ashe throws an explosive that detonates after a short delay or immediately when shot. The explosion from Dynamite deals 30 - 75 damage in a 5 meter radius and burns enemies for 100 damage over 5 seconds. 50% self damage. 2 second cast. 10 second cooldown.";
        ashe.heroAbility2Name = "Coach Gun";
        ashe.heroAbility2 = "Ashe blasts enemies in front of her with 15 bullets dealing 6 damage per bullet, knocking them away and propelling herself backward for added mobility. 10 second cooldown. Can't headshot.";
        ashe.heroUltimateName = "B.O.B";
        ashe.heroUltimate = "Ashe summons her trusted omnic sidekick, B.O.B., who charges forward up to 65 meters and knocks enemies into the air dealing 120 damage, then lays down suppressing fire with his arm cannons dealing 112 damage per second. Arm cannon range of 40 meters. Duration 1200 health or 10 seconds after collision.";
        ashe.heroTipsAndTricks = "On PC, aim at your target, throw your dynamite, and your crosshair will follow the dynamite. Shoot once the dynamite has reached your target to immediately detonate it. The \"crosshair follow\" does not work on console, but an alternative to easily hit the dynamite is to fire your coach gun.";
        ashe.heroClass = "damage";
        ashe.heroImage = R.drawable.ashe_smallerportrait;
        heroes.add(ashe);

        Hero baptiste = new Hero();
        baptiste.heroName = "Baptiste";
        baptiste.heroDifficulty = 3;
        baptiste.heroStrengths = "Strong healing and team utility";
        baptiste.heroWeaknesses = "Will be targeted";
        baptiste.heroHealth= 200;
        baptiste.heroArmor = 0;
        baptiste.heroShield = 0;
        baptiste.heroLeftClickDamage = "Baptiste’s three-round-burst Biotic Launcher deals 12.5 damage per bullet. Shooting 3 round per second with a 0.35 second cooldown. 45 rounds. 1.5 second reload. Hitscan.";
        baptiste.heroRightClickDamage = "Baptiste's Biotic launcher also doubles as a healing device, lobbing projectiles that heal for 60 points in a 3 meter radius. Shooting 1.25 shots per second. 10 rounds. 1.5 second reload. Does not self heal.";
        baptiste.heroSpeed = "5.5 meters per second";
        baptiste.heroPassiveName = "Exo Boots";
        baptiste.heroPassive = "Baptist can jump higher after crouching for 1 second.";
        baptiste.heroAbility1Name = "Regenerative Burst";
        baptiste.heroAbility1 = "Baptiste activates an intense regenerative burst that heals himself and nearby allies for 30 points per second for 5 seconds. 10 meter radius. 0.3 second cast. 15 second cooldown.";
        baptiste.heroAbility2Name = "Immortality Field";
        baptiste.heroAbility2 = "Baptiste places a generator which projects a 6 meter radius shield with 250 health for 8 seconds. Allies in the radius restored to 20% of their hp and can't drop below 20% of their hp. 1 second cast time. 20 second cooldown.";
        baptiste.heroUltimateName = "Amplification Matrix";
        baptiste.heroUltimate = "Baptiste creates a 5 meters wide, 4 meters tall matrix within 30 meters that doubles the damage and healing effects of friendly projectiles that pass through it. Lasts 8 seconds.";
        baptiste.heroTipsAndTricks = "Use exo boots in fights against non-hitscan enemies.";
        baptiste.heroClass = "support";
        baptiste.heroImage = R.drawable.baptiste_smallerportrait;
        heroes.add(baptiste);

        Hero bastion = new Hero();
        bastion.heroName = "Bastion";
        bastion.heroDifficulty = 1;
        bastion.heroStrengths = "Deals lots of damage";
        bastion.heroWeaknesses = "Stationary when in Sentry mode";
        bastion.heroHealth = 200;
        bastion.heroArmor = 100;
        bastion.heroShield = 0;
        bastion.heroLeftClickDamage = "In Recon mode, Bastion is fully mobile, outfitted with a sub-machine gun that fires 8 bullets per second dealing 6-20 damage per shot over 25 - 45 meters. 35 rounds. 1.5 second reload. / In Sentry mode, Bastion is a stationary powerhouse equipped with a gatling gun firing 30 bullet per second dealing 7.5 - 15 damage per shot over 35 - 55 meters. 300 rounds. 2 second reload.";
        bastion.heroRightClickDamage = "Bastion performs Self-Repair healing 75 health per second for 4.3 seconds. 7 second cooldown.";
        bastion.heroSpeed = "5.5 meters per second";
        bastion.heroPassiveName = "Ironclad";
        bastion.heroPassive = "Bastion's receives +20% damage resistance while transformed.";
        bastion.heroAbility1Name = "Reconfigure";
        bastion.heroAbility1 = "Bastion transforms between Recon and Sentry mode. It takes 1 second to transform into sentry and 0.5 seconds into recon. Reloads your weapon. 0 second cooldown.";
        bastion.heroAbility2Name = "None";
        bastion.heroAbility2 = "";
        bastion.heroUltimateName = "Configuration: Tank";
        bastion.heroUltimate = "Bastion takes 1.5 seconds transforming into a tank. Bastion can fire explosive shells at 44 m/s every second dealing 205 damage for direct hits and 70-145 damage in a 4 meter radius. Tank lasts for 8 seconds. While in tank mode, Bastion is immune to knockback.";
        bastion.heroTipsAndTricks = "Keep moving to different locations so enemies don't easily take you out.";
        bastion.heroClass = "damage";
        bastion.heroImage = R.drawable.bastion_smallerportrait;
        heroes.add(bastion);

        Hero brigitte = new Hero();
        brigitte.heroName = "Brigitte";
        brigitte.heroDifficulty = 1;
        brigitte.heroStrengths = "Good at protecting important allies";
        brigitte.heroWeaknesses = "Weak when isolated";
        brigitte.heroHealth = 200;
        brigitte.heroArmor = 50;
        brigitte.heroShield = 0;
        brigitte.heroLeftClickDamage = "Brigitte’s melee weapon has an extended range of 6 meters, enabling her to strike multiple enemies with a single swing dealing 35 damage. 2 swings per second.";
        brigitte.heroRightClickDamage = "Brigitte deploys a frontal energy barrier to absorb 500 points of damage. -30% movement speed (3.85 m/s). Shield regenerates 100 hp per second. 3 second cooldown if destroyed.";
        brigitte.heroSpeed = "5.5 meters per second";
        brigitte.heroPassiveName = "Inspire";
        brigitte.heroPassive = "When Brigitte strikes an enemy with her flail, all allies within 20 meters are healed for 16.67 health per second for 6 seconds. 1 second cooldown.";
        brigitte.heroAbility1Name = "Shield Bash + Whip Shot";
        brigitte.heroAbility1 = "Once her Barrier Shield is deployed, Brigitte can dash forward 6.8 meters to stun an enemy for 1 second and deal 5 points of damage. 7 second cooldown. / Brigitte throws her flail 20 meters, dealing 70 damage and knocking an enemy away from her. 40 m/s projectile speed. 4 second cooldown.";
        brigitte.heroAbility2Name = "Repair Pack";
        brigitte.heroAbility2 = "Brigitte throws a Repair Pack that can heal an ally for 150 hp. Any healing over that ally’s maximum health provides them with armor instead. 30 m/s projectile speed. 30 meter range. 5 second duration. 6 second cooldown.";
        brigitte.heroUltimateName = "Rally";
        brigitte.heroUltimate = "Brigitte moves 30% faster (7 m/s) and provides allies with 30 armor per second until a maximum of 150. Speed buff lasts 10 seconds while Armor lasts for 30.";
        brigitte.heroTipsAndTricks = "Protect vulnerable allies.";
        brigitte.heroClass = "support";
        brigitte.heroImage = R.drawable.brigitte_smallerportrait;
        heroes.add(brigitte);

        Hero dva = new Hero();
        dva.heroName = "D.Va";
        dva.heroDifficulty = 2;
        dva.heroStrengths = "Good Mobility";
        dva.heroWeaknesses = "Low Range";
        dva.heroHealth = 550;
        dva.heroArmor = 200;
        dva.heroShield = 0;
        dva.heroLeftClickDamage = "D.Va's mech shoots 11 pellets per shot dealing 0.6 - 2 damage per pellet over 10 - 20 meters. 6.67 shots per second. Unlimited rounds. 2.75 m/s movement speed. / While outside of her mech, D.Va can continue the fight with a mid-range automatic blaster that fires 7 rounds per second and dealing 14 damage per shot. ";
        dva.heroRightClickDamage = "D.Va projects a 15 meter forward facing defense matrix which blocks incoming projectiles for 2 seconds. 2 second cooldown. 8 second recharge.";
        dva.heroSpeed = "5.5 meters per second";
        dva.heroPassiveName = "Eject";
        dva.heroPassive = "D.Va takes 1 second to eject out of her mech when destroyed.";
        dva.heroAbility1Name = "Boosters";
        dva.heroAbility1 = "D.Va’s mech booster allow her to move in any direction at 12.5 m/s for 2 seconds. Running through enemies deals 10 damage and knocks them back. 5 second cooldown.";
        dva.heroAbility2Name = "Micro Missiles";
        dva.heroAbility2 = "D.Va fires 11 missiles per second for 1.6 seconds dealing 7 damage for direct hits and 4 damage within 1.5 meters. 0.5 second cast. 8 second cooldown.";
        dva.heroUltimateName = "Self-Destruct / Call Mech";
        dva.heroUltimate = "D.Va ejects from her mech and sets its reactor to explode in 3 seconds, dealing 0 - 1000 damage within 20 meters. / If her mech is destroyed, D.Va can call down a new mech dealing 50 damage to enemies.";
        dva.heroTipsAndTricks = "Disrupt the enemy, go behind enemy lines.";
        dva.heroClass = "tank";
        dva.heroImage = R.drawable.dva_smallerportrait;
        heroes.add(dva);

        Hero doomfist = new Hero();
        doomfist.heroName = "Doomfist";
        doomfist.heroDifficulty = 3;
        doomfist.heroStrengths = "Good at taking hits and disrupting enemy movement";
        doomfist.heroWeaknesses = "No long range damage";
        doomfist.heroHealth= 250;
        doomfist.heroArmor = 0;
        doomfist.heroShield = 0;
        doomfist.heroLeftClickDamage = "Doomfist fires a short-range burst of pellets from the knuckles of his fist dealing 11 damage per pellet. Its ammunition is automatically regenerated over a short time. 4 rounds. 3 shots per second. 0.75 seconds per missing round.";
        doomfist.heroRightClickDamage = "After charging up for 1 second, Doomfist lunges forward 6.5 - 20 meters and knocks an enemy back dealing 49 - 100 damage, and dealing additional an additional 50 damage if they impact a wall.";
        doomfist.heroSpeed = "5.5 meters per second";
        doomfist.heroPassiveName = "The Best Defense...";
        doomfist.heroPassive = "Doomfist generates +35 shield per enemy damaged with basic abilities (+75 for ultimate) until a maximum of 150 shields. Shields start to decay after 1 second at 3 shields per second.";
        doomfist.heroAbility1Name = "Rising Uppercut";
        doomfist.heroAbility1 = "Doomfist uppercuts enemies in front of him into the air dealing 50 damage within a 5 meter radius. 7 second cooldown.";
        doomfist.heroAbility2Name = "Seismic Slam";
        doomfist.heroAbility2 = "Doomfist leaps forward and smashes into the ground, knocking nearby enemies toward him and dealing 49 - 125 damage withing 8 - 15 meters (depending on height). 6 second cooldown.";
        doomfist.heroUltimateName = "Meteor Strike";
        doomfist.heroUltimate = "Doomfist leaps into the sky, then crashes to the ground, dealing 300 damage within 2 meters and 20 - 200 damage within 6 meters. 1 second cast. 4 second duration.";
        doomfist.heroTipsAndTricks = "Use Rocket Punch to interrupt ultimates or other abilities.";
        doomfist.heroClass = "damage";
        doomfist.heroImage = R.drawable.doomfist_smallerportrait;
        heroes.add(doomfist);

        Hero echo = new Hero();
        echo.heroName = "Echo";
        echo.heroDifficulty = 2;
        echo.heroStrengths = "Good at catching and finishing off enemies";
        echo.heroWeaknesses = "Vulnerable to poor positioning with flight";
        echo.heroHealth = 200;
        echo.heroArmor = 0;
        echo.heroShield = 0;
        echo.heroLeftClickDamage = "Echo fires 3 shots at once dealing 17 damage per shot. Shooting 3 shots per second. 75 m/s projectile speed. 15 ammo. 1.5 second reload. ";
        echo.heroRightClickDamage = "Echo fires a 6 sticky bombs that detonate after 1 second dealing 5 damage on impact and 25 damage in a 2 meter radius. Shoots 1 bomb every 0.065 seconds. 50 m/s projectile speed. 6 second cooldown. . ";
        echo.heroSpeed = "5.5 m/s";
        echo.heroPassiveName = "Glide";
        echo.heroPassive = "Echo glides falling at 4 m/s";
        echo.heroAbility1Name = "Flight";
        echo.heroAbility1 = "Echo surges forward at 8 m/s, then can fly freely for a short duration. 3 second duration. 6 second cooldown.";
        echo.heroAbility2Name = "Focusing Beam";
        echo.heroAbility2 = "Echo channels a beam for 2.5 seconds, dealing 50 damage or 200 damage to targets with less than half health.";
        echo.heroUltimateName = "Duplicate";
        echo.heroUltimate = "Echo duplicates a targeted enemy hero within 40 meters and gains use of their abilities for 15 seconds. 0.35 second cast. 1 second recovery.";
        echo.heroTipsAndTricks = "Understand how to play other heroes to get maximum value from your ultimate.";
        echo.heroClass = "damage";
        echo.heroImage = R.drawable.echo_smallerportrait;
        heroes.add(echo);

        Hero genji = new Hero();
        genji.heroName = "Genji";
        genji.heroDifficulty = 3;
        genji.heroStrengths = "High Mobility";
        genji.heroWeaknesses = "Beam attacks (can't deflect them)";
        genji.heroHealth = 200;
        genji.heroArmor = 0;
        genji.heroShield = 0;
        genji.heroLeftClickDamage = "Genji throws three shurikens each dealing 28 damage. 24 rounds. 1.5 second reload.";
        genji.heroRightClickDamage = "Genji throws three shuriken in a wider spread. 1.33 shots per second.";
        genji.heroSpeed = "6 meters per second";
        genji.heroPassiveName = "Cyber-Agility";
        genji.heroPassive = "Genji can climb walls and perform jumps in mid-air.";
        genji.heroAbility1Name = "Swift Strike";
        genji.heroAbility1 = "Genji darts 15 meters forward dealing 50 damage to enemies. If Genji eliminates a target, he can instantly use this ability again. 8 second cooldown.";
        genji.heroAbility2Name = "Deflect";
        genji.heroAbility2 = "Genji reflects an oncoming projectiles and sends them back to the enemy for 2 seconds. 8 second cooldown.";
        genji.heroUltimateName = "Dragonblade";
        genji.heroUltimate = "Genji brandishes his katana for 6 seconds. Genji can deliver 120 damage strikes to all targets within his 5 meter reach. Genji's speed increases to 8 meters per second.";
        genji.heroTipsAndTricks = "Use your mobility, try to be unpredictable while shooting at your enemy.";
        genji.heroClass = "damage";
        genji.heroImage = R.drawable.genji_smallerportrait;
        heroes.add(genji);

        Hero hanzo = new Hero();
        hanzo.heroName = "Hanzo";
        hanzo.heroDifficulty = 3;
        hanzo.heroStrengths = "Can one-shot most heroes.";
        hanzo.heroWeaknesses = "Hard to hit arrows.";
        hanzo.heroHealth = 200;
        hanzo.heroArmor = 0;
        hanzo.heroShield = 0;
        hanzo.heroLeftClickDamage = "Hanzo nocks and fires an arrow at his target dealing 29-125 damage per shot. 26 - 100 m/s projectile speed. 3.85 m/s movement speed. Stats depended on charge duration. 0.75 seconds until max charge. 0.5 seconds buffer.";
        hanzo.heroRightClickDamage = "NA";
        hanzo.heroSpeed = "5.5 meters per second";
        hanzo.heroPassiveName = "Wall Climb + Lunge";
        hanzo.heroPassive = "Jump at walls to climb at them. Hanzo can double jump going 7.5 meters. 5 second cooldown.";
        hanzo.heroAbility1Name = "Storm Arrow";
        hanzo.heroAbility1 = "Hanzo receives 6 storm arrows for 5 seconds which deal 70 damage each. He can fire 1 arrow every 0.3 seconds. 10 second cooldown.";
        hanzo.heroAbility2Name = "Sonic Arrow";
        hanzo.heroAbility2 = "Hanzo launches an arrow that contains a sonar tracking device. Any enemy within 10 meters is revealed. 12 second cooldown.";
        hanzo.heroUltimateName = "Dragonstrike";
        hanzo.heroUltimate = "Hanzo summons a Spirit Dragon which travels through the air in a line. It passes through walls in its way, dealing 200 damage per second to all enemies it encounters. 4 meter radius. Global range. 1.5 second cast.";
        hanzo.heroTipsAndTricks = "Stay in the back of your team and shoot arrows. Focus on important targets like supports.";
        hanzo.heroClass = "damage";
        hanzo.heroImage = R.drawable.hanzo_smallerportrait;
        heroes.add(hanzo);

        Hero junkrat = new Hero();
        junkrat.heroName = "Junkrat";
        junkrat.heroDifficulty = 2;
        junkrat.heroStrengths = "Area Damage";
        junkrat.heroWeaknesses = "Hard to hit his auto attacks";
        junkrat.heroHealth = 200;
        junkrat.heroArmor = 0;
        junkrat.heroShield = 0;
        junkrat.heroLeftClickDamage = "Junkrat's Frag Launcher lobs grenades exploding on their 3rd bounce or when they hit a character dealing 130 damage on direct hits and 12.5 - 80 damage to all enemies in a 2 meter radius. 5 rounds. 1.55 second reload. 25 m/s projectile speed. 1.66 rounds per second. Knocks back enemies and Junkrat.";
        junkrat.heroRightClickDamage = "Triggers Concussion Mine";
        junkrat.heroSpeed = "5.5 meters per second";
        junkrat.heroPassiveName = "Total Mayhem";
        junkrat.heroPassive = "Junkrat's deranged sense of humor persists past his death. If killed, he drops 6 live grenades which each deal 50 damage each within 2 meters. ";
        junkrat.heroAbility1Name = "Concussion Mine";
        junkrat.heroAbility1 = "Junkrat throws a mine which he can trigger dealing 120 damage to enemies within 3 meters and sending them flying. Can also be used to propel Junkrat through the air. 2 rounds. 17.5 m/s projectile speed. 8 second cooldown.";
        junkrat.heroAbility2Name = "Steel Trap";
        junkrat.heroAbility2 = "Junkrat tosses out a giant, metal-toothed trap. Should an enemy wander within 1 meter of the trap, it clamps on, dealing 80 damage, stunning for 1 second and rooting for another 3 seconds. 10 second cooldown. Traps have 100HP and can be destroyed.";
        junkrat.heroUltimateName = "RIP-Tire";
        junkrat.heroUltimate = "Junkrat revs up a motorized tire bomb and sends it rolling across the battlefield, climbing over walls and obstacles. He can remotely detonate the RIP-Tire or wait 10 seconds to deal 60-600 damage to enemies caught in within 10 meters of the blast, or just wait for it to explode on its own. 1 second cast.";
        junkrat.heroTipsAndTricks = "Stay in the back shooting grenades and dealing damage. Concussion Mine can be used to move around faster. You are vulnerable while using RIP-Tire, so use it from a safe place.";
        junkrat.heroClass = "damage";
        junkrat.heroImage = R.drawable.junkrat_smallerportrait;
        heroes.add(junkrat);

        Hero lucio = new Hero();
        lucio.heroName = "Lucio";
        lucio.heroDifficulty = 1;
        lucio.heroStrengths = "Area Effect, Healing, Speed Boost";
        lucio.heroWeaknesses = "Focused often, Hard to hit auto attacks";
        lucio.heroHealth = 200;
        lucio.heroArmor = 0;
        lucio.heroShield = 0;
        lucio.heroLeftClickDamage = "Lúcio can hit his enemies with sonic projectiles dealing 20 damage per projectile. 20 rounds. 1.5 second reload. 0.52 seconds per shot. ";
        lucio.heroRightClickDamage = "Lúcio can knock his enemies back within 8 meters dealing 25 damage with a blast of sound. 4 second cooldown.";
        lucio.heroSpeed = "5.5 meters per second";
        lucio.heroPassiveName = "Wall Run";
        lucio.heroPassive = "Jump onto a wall to ride along it. Has +40% movement speed while wall riding.";
        lucio.heroAbility1Name = "Crossfade";
        lucio.heroAbility1 = "Lúcio continuously energizes himself — and teammates within 12 meters — with music. He can switch between two songs: one amplifies movement speed by 20%, while the other regenerates 16.25 (13 self) health per second. 0.8 second buffer.";
        lucio.heroAbility2Name = "Amp It Up";
        lucio.heroAbility2 = "Lúcio increases the volume on his speakers, boosting the effects of his songs for 3 seconds. Increases the healing done to 46.8 (35 self) health per second and the speed to 50%. 12 second cooldown.";
        lucio.heroUltimateName = "Sound Barrier";
        lucio.heroUltimate = "Protective waves radiate out from Lúcio’s Sonic Amplifier, providing him and allies within 30 meters with 750 health shields for 6.25 seconds. 0.8 second cast.";
        lucio.heroTipsAndTricks = "Stay with your team and use your ultimate when pushing or getting pushed.";
        lucio.heroClass = "support";
        lucio.heroImage = R.drawable.lucio_smallerportrait;
        heroes.add(lucio);

        Hero mccree = new Hero();
        mccree.heroName = "McCree";
        mccree.heroDifficulty = 2;
        mccree.heroStrengths = "High Burst Damage";
        mccree.heroWeaknesses = "Weak at long range";
        mccree.heroHealth = 200;
        mccree.heroArmor = 0;
        mccree.heroShield = 0;
        mccree.heroLeftClickDamage = "McCree fires off a round dealing 20-70 damage over 20 - 40 meters. 6 rounds. 1.5 second reload. 2 shots per second.";
        mccree.heroRightClickDamage = "McCree can fan the Peacekeeper’s hammer dealing 25-50 damage per shot to swiftly unload the entire cylinder. .11 seconds per shot. 0.3 second charge. Can't headshot.";
        mccree.heroSpeed = "5.5 meters per second";
        mccree.heroPassiveName = "None";
        mccree.heroPassive = "";
        mccree.heroAbility1Name = "Combat Roll";
        mccree.heroAbility1 = "McCree dives 6 meters in the direction he’s moving, effortlessly reloading his Peacekeeper in the process. 6 second cooldown.";
        mccree.heroAbility2Name = "Flashbang";
        mccree.heroAbility2 = "McCree heaves a blinding grenade that explodes after 7 meters. The blast stuns enemies for 0.8 seconds in a 3 meter radius and dealing 25 damage. 0.35 second cast. 10 second cooldown.";
        mccree.heroUltimateName = "Deadeye";
        mccree.heroUltimate = "McCree takes a few precious moments to aim dealing 100-550 damage after aiming for a maximum of 6 seconds; when he’s ready to fire, he shoots every enemy in his line of sight. The weaker his targets are, the faster he’ll line up a killshot. 0.2 second cast. 2 m/s movement speed. ";
        mccree.heroTipsAndTricks = "Pick off enemies trying to flank your team.";
        mccree.heroClass = "damage";
        mccree.heroImage = R.drawable.mccree_smallerportrait;
        heroes.add(mccree);

        Hero mei = new Hero();
        mei.heroName = "Mei";
        mei.heroDifficulty = 2;
        mei.heroStrengths = "Can freeze enemies, Can temporarily wall of areas";
        mei.heroWeaknesses = "Hard to freeze multiple people";
        mei.heroHealth = 250;
        mei.heroArmor = 0;
        mei.heroShield = 0;
        mei.heroLeftClickDamage = "Mei’s blaster unleashes a concentrated, short-range 10 meter stream of frost that deals 55 damage per second, slows, and ultimately freezes enemies in place after 1.5 seconds. 200 rounds. 20 shots per second. 1.5 second reload. 20 m/s projectile speed.";
        mei.heroRightClickDamage = "Mei can also use her blaster to shoot icicle-like projectiles dealing 75 damage. Uses 20 rounds per shot. 0.38 second cast. 1.25 shots per second. 120 m/s projectile speed.";
        mei.heroSpeed = "5.5 meters per second";
        mei.heroPassiveName = "None";
        mei.heroPassive = "";
        mei.heroAbility1Name = "Cryo-Freeze";
        mei.heroAbility1 = "Mei instantly surrounds herself with a block of thick ice. She heals 37.5 health per second for 4 seconds and ignores damage while encased, but cannot move or use abilities. 12 second cooldown.";
        mei.heroAbility2Name = "Ice Wall";
        mei.heroAbility2 = "Mei generates an enormous ice wall at a maximum of 35 meters away that obstructs lines of sight, stops movement, and blocks attacks for 5 seconds. 5 wall segments. Each wall segment has 400 health. 10 second cooldown.";
        mei.heroUltimateName = "Blizzard";
        mei.heroUltimate = "Mei deploys a weather-modification drone that emits gusts of wind and snow in a 10 meter area for 5 seconds. Enemies caught in the blizzard are slowed and take 20 damage per second over the full duration; those who linger too long are frozen solid. 1.5 second cast.";
        mei.heroTipsAndTricks = "Protect teammates with ice wall and use your ultimate in combination with your team.";
        mei.heroClass = "damage";
        mei.heroImage = R.drawable.mei_smallerportrait;
        heroes.add(mei);

        Hero mercy = new Hero();
        mercy.heroName = "Mercy";
        mercy.heroDifficulty = 2;
        mercy.heroStrengths = "Can revive dead allies for a surprise attack";
        mercy.heroWeaknesses = "She is easily targeted";
        mercy.heroHealth = 200;
        mercy.heroArmor = 0;
        mercy.heroShield = 0;
        mercy.heroLeftClickDamage = "Mercy maintains a beam healing an ally 50 (60 while ulting) health per second within 15 meters (range of 30 and radius of 10 meters while ulting). Lasts for 1.4 seconds after losing line of sight. Mercy can also use her Caduceus Blaster dealing 20 damage per shot shooting at 40 m/s (100 while ulting and unlimited ammo). 5 shots per second.";
        mercy.heroRightClickDamage = "Increases damage of an ally by 30% within 15 meters (range of 30 and radius of 10 meters while ulting). Lasts for 2 seconds after losing line of sight.";
        mercy.heroSpeed = "5.5 meters per second";
        mercy.heroPassiveName = "Angelic Descent + Regeneration";
        mercy.heroPassive = "Mercy can slow the speed of her descent. Mercy also heals 20 health per second after not being damaged for 1 seconds.";
        mercy.heroAbility1Name = "Guardian Angel";
        mercy.heroAbility1 = "Mercy flies towards a targeted ally at 20 m/s for a maximum 30 meter distance. 1.5 second cooldown.";
        mercy.heroAbility2Name = "Resurrect";
        mercy.heroAbility2 = "Mercy brings dead allies within 5 meters back into the fight with full health. 1.75 second cast. 1.375 m/s movement speed. 30 second cooldown.";
        mercy.heroUltimateName = "Valkyrie";
        mercy.heroUltimate = "Valkyrie enhances all of Mercy's abilities and increases her movement speed to 9 m/s for 15 seconds.";
        mercy.heroTipsAndTricks = "Support your team and play safe knowing enemies will target you.";
        mercy.heroClass = "support";
        mercy.heroImage = R.drawable.mercy_smallerportrait;
        heroes.add(mercy);

        Hero moira = new Hero();
        moira.heroName = "Moira";
        moira.heroDifficulty = 2;
        moira.heroStrengths = "Flexibility in dealing with different situations";
        moira.heroWeaknesses = "Dies easily in 1v1";
        moira.heroHealth = 200;
        moira.heroArmor = 0;
        moira.heroShield = 0;
        moira.heroLeftClickDamage = "Using her left hand, Moira expends biotic energy to heal allies in front of her for 80 hp over 4 seconds. 30 m/s projectile speed. 15 meter range. 0.3 second cast. Duration up to 9 seconds.";
        moira.heroRightClickDamage = "Her right hand fires a 20 meter range beam weapon that saps enemies’ health dealing 50 damage per second and healing Moira 33 health per second. Replenishes her biotic energy.";
        moira.heroSpeed = "5.5 meters per second";
        moira.heroPassiveName = "None";
        moira.heroPassive = "";
        moira.heroAbility1Name = "Fade";
        moira.heroAbility1 = "Disappear, move 18.75 m/s, and become invulnerable, but you cannot shoot. Lasts 0.8 seconds. 6 second cooldown.";
        moira.heroAbility2Name = "Biotic Orb";
        moira.heroAbility2 = "Moira launches a rebounding biotic sphere; she can choose between a regeneration effect that heals the allies it passes through for 75 health per second, or a decay effect that deals 50 damage per second to enemies. 20 m/s projectile speed (5.5 m/s while tethered. 10 second cooldown.";
        moira.heroUltimateName = "Coalescence";
        moira.heroUltimate = "Moira channels a 30 meter range beam that both heals allies for 140 hp per second and bypasses barriers to damage her enemies for 70 hp per second. While channeling this ability, Moira’s movement speed increases to 9 m/s, but she cannot perform any other actions. 0.5 second cast. Lasts 8 seconds.";
        moira.heroTipsAndTricks = "Use damage orb for poking and healing orb for engagements. Use your ultimate before your teammates die.";
        moira.heroClass = "support";
        moira.heroImage = R.drawable.moira_smallerportrait;
        heroes.add(moira);

        Hero orisa = new Hero();
        orisa.heroName = "Orisa";
        orisa.heroDifficulty = 2;
        orisa.heroStrengths = "Protects the team front line";
        orisa.heroWeaknesses = "Can't deal with enemies at range";
        orisa.heroHealth = 200;
        orisa.heroArmor = 200;
        orisa.heroShield = 0;
        orisa.heroLeftClickDamage = "Orisa’s automatic projectile cannon delivers sustained damage firing 12.5 rounds per second dealing 11 damage each. Her movement decreases 30% (2.75 m/s). 72 m/s projectile speed. 150 rounds. 2.55 second reload.";
        orisa.heroRightClickDamage = "Orisa launches a graviton charge which she can detonate, slowing enemies within 7.5 meters and pulling them towards the explosion. 20 m/s projectile. 0.33 second cast. Lasts 0.45 seconds. 8 second cooldown.";
        orisa.heroSpeed = "5.5 meters per second";
        orisa.heroPassiveName = "None";
        orisa.heroPassive = "";
        orisa.heroAbility1Name = "Fortify ";
        orisa.heroAbility1 = "Orisa temporarily receives +50% damage reduction and immunity to cc. Lasts 4 seconds. 10 second cooldown (only starts when duration ends).";
        orisa.heroAbility2Name = "Protective Barrier";
        orisa.heroAbility2 = "Orisa throws out a stationary barrier that can protect her and her allies from enemy fire. The barrier has 900 hp and lasts 20 seconds. 19 m/s projectile speed. 8 second cooldown.";
        orisa.heroUltimateName = "Supercharger";
        orisa.heroUltimate = "Orisa deploys a device which increases ally damage output by 50%. Only impacts allies within 25 meters and in line of sight of the device. 1 second cast. 200 hp device. Lasts 15 seconds.";
        orisa.heroTipsAndTricks = "Don't reload too often. Place Supercharger in safe locations.";
        orisa.heroClass = "tank";
        orisa.heroImage = R.drawable.orisa_smallerportrait;
        heroes.add(orisa);

        Hero pharah = new Hero();
        pharah.heroName = "Pharah";
        pharah.heroDifficulty = 2;
        pharah.heroStrengths = "High Burst Damage";
        pharah.heroWeaknesses = "She is easily targeted while in the air";
        pharah.heroHealth = 200;
        pharah.heroArmor = 0;
        pharah.heroShield = 0;
        pharah.heroLeftClickDamage = "Pharah’s primary weapon launches rockets that deal 120 damage on direct hits and 20 - 80 damage (10 - 32.5 self) in a 3 meter radius. 6 rounds. 1.5 second reload. 1.33 shots per second. 35 m/s projectile speed. ";
        pharah.heroRightClickDamage = "NA";
        pharah.heroSpeed = "5.5 meters per second";
        pharah.heroPassiveName = "Hover jets";
        pharah.heroPassive = "Hold to hover in the air for 2 seconds. 2 second cooldown";
        pharah.heroAbility1Name = "Concussive Blast";
        pharah.heroAbility1 = "Pharah looses a wrist rocket that knocks back any enemies it strikes in a 8 meter radius. Knockback also affects Pharah. 50 m/s projectile speed. 9 second cooldown.";
        pharah.heroAbility2Name = "Jump jet";
        pharah.heroAbility2 = "Propelled by her suit’s thrusters, Pharah soars 25 meters into the air at 20 m/s. 10 second cooldown";
        pharah.heroUltimateName = "Barrage";
        pharah.heroUltimate = "Pharah directs a continuous salvo of 30 mini-rockets per second dealing 40 damage per rocket for 3 seconds to destroy groups of enemies. Pharah cannot move while Barrage is active. Deals self damage. 28.5 m/s projectile speed.";
        pharah.heroTipsAndTricks = "Stay in the air dealing damage from above (but be careful of snipers).";
        pharah.heroClass = "damage";
        pharah.heroImage = R.drawable.pharah_smallerportrait;
        heroes.add(pharah);

        Hero reaper = new Hero();
        reaper.heroName = "Reaper";
        reaper.heroDifficulty = 1;
        reaper.heroStrengths = "Good at Flanking and taking out tanks";
        reaper.heroWeaknesses = "Weak at long range";
        reaper.heroHealth = 250;
        reaper.heroArmor = 0;
        reaper.heroShield = 0;
        reaper.heroLeftClickDamage = "Reaper tears enemies apart with twin shotguns shooting 20 pellets dealing 2.1 - 7 damage each over 10 - 20 meters. 8 rounds. 1.5 second reload. 2 shots per second.. ";
        reaper.heroRightClickDamage = "NA";
        reaper.heroSpeed = "5.5 meters per second";
        reaper.heroPassiveName = "The Reaping";
        reaper.heroPassive = "40% of damage dealt is restored as hp.";
        reaper.heroAbility1Name = "Wraith Form";
        reaper.heroAbility1 = "Reaper becomes a shadow for a 3 seconds. While active, he takes no damage, is able to pass through enemies and moves 7.1 m/s, but cannot fire his weapons or use other abilities.  8 second cooldown.";
        reaper.heroAbility2Name = "Shadow Step";
        reaper.heroAbility2 = "After marking a destination up to a maximum of 35 meters, Reaper disappears and reappears at that location. 2 second duration. 1.5 second cast. 10 second cooldown.";
        reaper.heroUltimateName = "Death Blossom";
        reaper.heroUltimate = "In a blur of motion, Reaper empties both Hellfire Shotguns at breakneck speed, dealing 170 damage per second to all nearby enemies for 3 seconds in an 8 meter radius.";
        reaper.heroTipsAndTricks = "Target and kill tanks. Shadow Step behind Bastion in Sentry mode to catch him off guard.";
        reaper.heroClass = "damage";
        reaper.heroImage = R.drawable.reaper_smallerportrait;
        heroes.add(reaper);

        Hero reinhardt = new Hero();
        reinhardt.heroName = "Reinhardt";
        reinhardt.heroDifficulty = 2;
        reinhardt.heroStrengths = "High damage and can push very well";
        reinhardt.heroWeaknesses = "Weak at long range";
        reinhardt.heroHealth = 300;
        reinhardt.heroArmor = 200;
        reinhardt.heroShield = 0;
        reinhardt.heroLeftClickDamage = "Reinhardt’s Rocket Hammer deals 75 damage in a 5 meter range with every swing. 1.1 swings per second.";
        reinhardt.heroRightClickDamage = "Reinhardt projects a broad, forward-facing energy shield slowing his movement speed to 2.75 meters per second, which can absorb up to 2000 damage before it is destroyed. Reinhardt's shield will regenerate 200 health per second after not being used for 2 seconds. Though Reinhardt can protect himself and his companions behind the shield, he cannot attack while sustaining it. 5 second cooldown if destroyed.";
        reinhardt.heroSpeed = "5.5 meters per second";
        reinhardt.heroPassiveName = "None";
        reinhardt.heroPassive = "";
        reinhardt.heroAbility1Name = "Charge";
        reinhardt.heroAbility1 = "Reinhardt charges forth going 16.66 meters per second in a straight line for 3 seconds, grabbing hold of enemies in his path dealing 50 damage. If he collides with a wall, foes he’s carrying suffer 300 damage. 10 second cooldown (3 if interrupted).";
        reinhardt.heroAbility2Name = "Fire Strike";
        reinhardt.heroAbility2 = "By whipping his Rocket Hammer forward, Reinhardt slings a flaming projectile which pierces and deals 100 damage to any enemies it touches. 26.66 m/s projectile speed. 6 second cooldown.";
        reinhardt.heroUltimateName = "Earth Shatter";
        reinhardt.heroUltimate = "Reinhardt forcefully slams his rocket hammer into the ground, dealing 50 damage and knocking down enemies in front of him for 2.5 seconds.";
        reinhardt.heroTipsAndTricks = "Protect your team with your shield.";
        reinhardt.heroClass = "tank";
        reinhardt.heroImage = R.drawable.reinhardt_smallerportrait;
        heroes.add(reinhardt);

        Hero roadhog = new Hero();
        roadhog.heroName = "Roadhog";
        roadhog.heroDifficulty = 2;
        roadhog.heroStrengths = "High damage";
        roadhog.heroWeaknesses = "Weak at long range";
        roadhog.heroHealth = 600;
        roadhog.heroArmor = 0;
        roadhog.heroShield = 0;
        roadhog.heroLeftClickDamage = "Roadhog's Scrap Gun fires 25 bits of shrapnel dealing 1.6 - 6 damage per fragment over 11 - 22 meters (45 - 150 damage per shot). 5 rounds. 2 second reload. 1.3 shots per second. 57 m/s projectile speed.";
        roadhog.heroRightClickDamage = "Roadhog's Scrap Gun launches a shrapnel ball that detonates farther away, scattering metal fragments from the point of impact. The ball deals 50 damage while the shrapnel stays the same. The drop off changes to 15 - 30 meters. 1.43 shots per second.";
        roadhog.heroSpeed = "5.5 meters per second";
        roadhog.heroPassiveName = "None";
        roadhog.heroPassive = "";
        roadhog.heroAbility1Name = "Chain Hook";
        roadhog.heroAbility1 = "Roadhog hurls his chain at 40 m/s for a maximum distance of 20 meters at a target; if it catches, he yanks them into close range dealing 30 damage. 0.3 second cast. 6 second cooldown.";
        roadhog.heroAbility2Name = "Take a Breather";
        roadhog.heroAbility2 = "Roadhog restores 300 health for 1 second and gains 50% damage reduction over 2 seconds. 0.6 second cast time. 0.4 seconds recovery. 8 second cooldown.";
        roadhog.heroUltimateName = "Whole Hog";
        roadhog.heroUltimate = "After cramming a top-loader onto his Scrap Gun, Roadhog pours in ammo. For 5.5 seconds, he can crank out a stream of 128 shrapnel bits that knockback enemies 10 m/s and deal 7 damage per pellet. 4.125 m/s movement speed. 0.5 second cast.";
        roadhog.heroTipsAndTricks = "Chain targets and bring them in for an easy kill.";
        roadhog.heroClass = "tank";
        roadhog.heroImage = R.drawable.roadhog_smallerportrait;
        heroes.add(roadhog);

        Hero sigma = new Hero();
        sigma.heroName = "Sigma";
        sigma.heroDifficulty = 3;
        sigma.heroStrengths = "Protecting important allies and taking damage";
        sigma.heroWeaknesses = "Low damage";
        sigma.heroHealth = 300;
        sigma.heroArmor = 0;
        sigma.heroShield = 100;
        sigma.heroLeftClickDamage = "Sigma launches two gravitic charges, which bounce off walls and implode after a short duration, damaging direct enemies for 55 and 9 - 30 within a 3 meter radius. 22 range. 0.67 shots per second. ";
        sigma.heroRightClickDamage = "Experimental Barrier";
        sigma.heroSpeed = "5.5 m/s";
        sigma.heroPassiveName = "None";
        sigma.heroPassive = "";
        sigma.heroAbility1Name = "Kinetic Grasp";
        sigma.heroAbility1 = "Sigma freezes incoming projectiles in midair within 3 meters for 2 seconds, converting 60% of their damage into shields (max 400). 12 second cooldown.";
        sigma.heroAbility2Name = "Accretion";
        sigma.heroAbility2 = "Sigma gathers a mass of debris and flings it at an enemy dealing 70 damage on direct hits and  12 - 40 splash within 2.5 meters. Knocks heroes back 4 meters on direct hits and 1 - 2 meters in the explosion radius. Knocks enemies down for 0.8 seconds. 0.65 second cast. 10 second cooldown.";
        sigma.heroUltimateName = "Gravitic Flux";
        sigma.heroUltimate = "Unleashing his full powers, Sigma takes flight, lifts enemies in a targeted 7 meter radius area, and launches them into the sky for 2 seconds dealing 50 damage before slamming them back down in 0.6 seconds dealing an additional 50% of their max hp. 7.15 m/s movement speed.";
        sigma.heroTipsAndTricks = "Be careful to not get interrupted while ulting. Use abilities carefully because your abilities have long cooldowns. ";
        sigma.heroClass = "tank";
        sigma.heroImage = R.drawable.sigma_smallerportrait;
        heroes.add(sigma);

        Hero soldier_76 = new Hero();
        soldier_76.heroName = "Soldier 76";
        soldier_76.heroDifficulty = 1;
        soldier_76.heroStrengths = "Good damage, healing, and mobility";
        soldier_76.heroWeaknesses = "Weak at longer ranges";
        soldier_76.heroHealth = 200;
        soldier_76.heroArmor = 0;
        soldier_76.heroShield = 0;
        soldier_76.heroLeftClickDamage = "Soldier: 76’s fully-automatic rifle deals 10 - 20 damage over 30 - 50 meters. 25 rounds. 1.55 second reload. 8.66 shots per second.";
        soldier_76.heroRightClickDamage = "Tiny rockets spiral out of Soldier: 76’s Pulse Rifle in a single burst. The rockets’ explosion deals 120 damage on direct hits and 40 -80 (20 - 40 self) to enemies in a 3 meter radius. 50 m/s projectile speed. 8 second cooldown. Can headshot.";
        soldier_76.heroSpeed = "5.5 meters per second";
        soldier_76.heroPassiveName = "None";
        soldier_76.heroPassive = "";
        soldier_76.heroAbility1Name = "Sprint";
        soldier_76.heroAbility1 = "Soldier: 76 can sprint at 8.33 m/s. Can't do any other action during sprint. Can't shoot or reload 0.3 seconds after sprinting.";
        soldier_76.heroAbility2Name = "Biotic field";
        soldier_76.heroAbility2 = "Soldier: 76 plants a biotic emitter on the ground that last for 5 seconds. It restores 40 health per second to allies within the 5 meter field. 15 second cooldown";
        soldier_76.heroUltimateName = "Tactical Visor";
        soldier_76.heroUltimate = "Soldier: 76’s pinpoint targeting visor “locks” his aim on the threat closest to his crosshairs. If an enemy leaves his line of sight, Soldier: 76 can quickly switch to another target. Tactical Visor lasts for 6 seconds. Reload speed increased to 0.75 seconds. 1.4 second cast.";
        soldier_76.heroTipsAndTricks = "Fire Helix rockets at the enemy's feet to be more accurate.";
        soldier_76.heroClass = "damage";
        soldier_76.heroImage = R.drawable.soldier_76_smallerportrait;
        heroes.add(soldier_76);

        Hero sombra = new Hero();
        sombra.heroName = "Sombra";
        sombra.heroDifficulty = 3;
        sombra.heroStrengths = "Good at disrupting enemies";
        sombra.heroWeaknesses = "No long range damage";
        sombra.heroHealth = 200;
        sombra.heroArmor = 0;
        sombra.heroShield = 0;
        sombra.heroLeftClickDamage = "Sombra’s fully-automatic machine pistol fires 20 rounds per second dealing 2.4 - 8 damage each. Falloff 15 - 35 meters. 60 rounds. 1.5 second reload. 2.7 degree spread angle.";
        sombra.heroRightClickDamage = "Sombra hacks enemies within 15 meters to temporarily stop them from using their abilities for 6 seconds, or hacks first aid kits to spawn faster and make them useless to her opponents for 60 seconds. Taking damage interrupts the hacking. 8 second cooldown on enemies, 6 seconds for health-pack, or 2 seconds if interrupted.";
        sombra.heroSpeed = "5.5 meters per second";
        sombra.heroPassiveName = "Opportunist";
        sombra.heroPassive = "Enemies with less than 50% of their hp are revealed.";
        sombra.heroAbility1Name = "Stealth";
        sombra.heroAbility1 = "Sombra becomes invisible for 6 seconds, during which her speed is boosted 50% (8.8 m/s). Attacking, using offensive abilities, walking within 2 meters of an enemy, or taking damage disables her camouflage. 0.7 second cast. 6 second cooldown.";
        sombra.heroAbility2Name = "Translocator";
        sombra.heroAbility2 = "Sombra tosses out a translocator beacon. She can instantly return to the beacon’s location while it is active you can only have one beacon at a time. (including when it’s in mid-flight). The beacon has 5 hp. 0.7 second cast. 19 m/s projectile speed. 4 second cooldown (2 if self-canceled).";
        sombra.heroUltimateName = "EMP";
        sombra.heroUltimate = "Sombra discharges electromagnetic energy in a 15 meter radius, destroying enemy barriers and shields and hacking all opponents caught in the blast. 0.5 cast. Lasts 6 seconds.";
        sombra.heroTipsAndTricks = "Use translocator for repositioning. Stealth voice line can be heard 15 meters away.";
        sombra.heroClass = "damage";
        sombra.heroImage = R.drawable.sombra_smallerportrait;
        heroes.add(sombra);

        Hero symmetra = new Hero();
        symmetra.heroName = "Symmetra";
        symmetra.heroDifficulty = 2;
        symmetra.heroStrengths = "High Burst Damage";
        symmetra.heroWeaknesses = "Weak at long range";
        symmetra.heroHealth = 100;
        symmetra.heroArmor = 0;
        symmetra.heroShield = 100;
        symmetra.heroLeftClickDamage = "Symmetra’s weapon emits a 12 meter range beam that homes in on a nearby enemy, dealing continuous damage that increases the longer it is connected 65/130/195. 70 rounds. 1.35 second reload. 7 rounds per second. Gains ammo if used against a barrier.";
        symmetra.heroRightClickDamage = "The projector can also release a charged energy ball which deals up to 120 damage on direct hits and 15 - 60 AoE. 1 second to charge and 0.55 seconds between shots. 20 m/s projectile speed. ";
        symmetra.heroSpeed = "5.5 meters per second";
        symmetra.heroPassiveName = "None";
        symmetra.heroPassive = "";
        symmetra.heroAbility1Name = "Sentry Turret";
        symmetra.heroAbility1 = "Symmetra sets up a small turret with 30 hp that automatically fires speed-reducing blasts slowing 20% and dealing 50 damage per second the nearest enemy within 10 meters. 3 turrets can be built on the battlefield at once. Max 3 turret storage. 1.5 second cast. 10 second cooldown";
        symmetra.heroAbility2Name = "Teleporter";
        symmetra.heroAbility2 = "Symmetra places a temporary teleporter exit pad at a distance and connects it to a teleporter entry pad at her current location. Allies (and some of their abilities, such as Junkrat’s RIP-Tire) can travel from the entry pad to the exit pad instantly. The teleporter has 50 health and 250 shield. 25 meter range. 0.8 second cast. 2 second deploy. 10 second duration. 12 second cooldown.";
        symmetra.heroUltimateName = "Photon Barrier";
        symmetra.heroUltimate = "Symmetra deploys a wide-radius generator that provides increased shielding to her entire team. Blocks 5000 points of damage. Lasts 15 seconds or until destroyed. 25 meter range.";
        symmetra.heroTipsAndTricks = "Send turrets through teleporter. 1 fully charged shot and 70% charged shot will kill a 200 health hero.";
        symmetra.heroClass = "damage";
        symmetra.heroImage = R.drawable.symmetra_smallerportrait;
        heroes.add(symmetra);

        Hero torbjorn = new Hero();
        torbjorn.heroName = "Torbjörn";
        torbjorn.heroDifficulty = 2;
        torbjorn.heroStrengths = "Defending chokepoints";
        torbjorn.heroWeaknesses = "Weak at long range";
        torbjorn.heroHealth = 200;
        torbjorn.heroArmor = 0;
        torbjorn.heroShield = 0;
        torbjorn.heroLeftClickDamage = "Torbjörn fires rivets at long range dealing 70 damage per shot. 1.67 shots per second. 55 m/s projectile speed. 18 rounds. 2 second reload. / Torbjörn uses his multipurpose hammer to build, upgrade and repair turrets healing 50 health. In a pinch, it can also be swung as a weapon dealing 55 damage swinging. 1.25 swings per second.";
        torbjorn.heroRightClickDamage = "Torbjörn ejects molten metal from his gun in a short, close-range burst shooting 10 pellet dealing 6 - 15 damage each. 10 - 20 meter falloff. 4.15 degree spread. 80 m/s projectile speed. 1.25 rounds per second. ";
        torbjorn.heroSpeed = "5.5 meters per second";
        torbjorn.heroPassiveName = "None";
        torbjorn.heroPassive = "";
        torbjorn.heroAbility1Name = "Build Turret";
        torbjorn.heroAbility1 = "Torbjörn constructs an enemy-tracking autocannon. He can use his Forge Hammer to repair or upgrade it, increasing its health and adding a second cannon barrel and a rocket launcher. The turret fires at enemies within 40 meters dealing 14 damage per round shooting 4 shots per second. 250 health. 15 meter deploy range. 3 second deploy time. 5 second cooldown (10 if destroyed). Can't headshot.";
        torbjorn.heroAbility2Name = "Overload";
        torbjorn.heroAbility2 = "Torbjörn gains 100 additional health as well as +30% attack speed, movement speed (7.15 m/s), and reload speed for a brief period. 12 second cooldown.";
        torbjorn.heroUltimateName = "Molten Core";
        torbjorn.heroUltimate = "Torbjörn creates pools of molten slag that deal 160 damage per second (190 if armored) for 10 second and preventing enemies from moving through key locations. Magma pools last 10 seconds.";
        torbjorn.heroTipsAndTricks = "Build your turret in a semi-protected spot that can still be an effective killer. Use Overload to survive a Tracer pulse bomb.";
        torbjorn.heroClass = "damage";
        torbjorn.heroImage = R.drawable.torbjorn_smallerportrait;
        heroes.add(torbjorn);

        Hero tracer = new Hero();
        tracer.heroName = "Tracer";
        tracer.heroDifficulty = 2;
        tracer.heroStrengths = "High damage and mobility";
        tracer.heroWeaknesses = "Weak at long range";
        tracer.heroHealth = 150;
        tracer.heroArmor = 0;
        tracer.heroShield = 0;
        tracer.heroLeftClickDamage = "Tracer rapid-fires both of her pistols shooting 20 shots per second dealing 3.6 - 12 damage per shot. 10 - 20 meter falloff. 40 rounds. 1.15 second reload. ";
        tracer.heroRightClickDamage = "";
        tracer.heroSpeed = "6 meters per second";
        tracer.heroPassiveName = "None";
        tracer.heroPassive = "";
        tracer.heroAbility1Name = "Blink";
        tracer.heroAbility1 = "Tracer zips 7.5 meters horizontally through space in the direction she’s moving. She stores up to three charges of the blink ability and generates 1 charge every 3 seconds. ";
        tracer.heroAbility2Name = "Recall";
        tracer.heroAbility2 = "Tracer bounds backward in time reloading her weapons and returning her health and position on the map to precisely where they were 3 seconds before. 1.25 second duration. 12 second cooldown";
        tracer.heroUltimateName = "Pulse Bomb";
        tracer.heroUltimate = "Tracer lobs a large bomb that adheres to any surface or unfortunate opponent it lands on dealing 5 damage if it sticks. After 1 second, the bomb explodes, dealing 300 damage to all enemies within its 3 meter radius.";
        tracer.heroTipsAndTricks = "Go behind enemy lines and distract them from the objective. After using Pulse Bomb, use Recall to get away. Can rebind blink to right click. ";
        tracer.heroClass = "damage";
        tracer.heroImage = R.drawable.tracer_smallerportrait;
        heroes.add(tracer);

        Hero widowmaker = new Hero();
        widowmaker.heroName = "Widowmaker";
        widowmaker.heroDifficulty = 2;
        widowmaker.heroStrengths = "High damage from long range and good mobility";
        widowmaker.heroWeaknesses = "Weak at close range";
        widowmaker.heroHealth = 200;
        widowmaker.heroArmor = 0;
        widowmaker.heroShield = 0;
        widowmaker.heroLeftClickDamage = "Should targets close to medium range, the rifle can also be fired in fully-automatic mode shooting 10 shots per second and dealing 13 damage per shot. 30 rounds. 1.5 second reload.";
        widowmaker.heroRightClickDamage = "Widowmaker’s versatile sniper rifle is ideal for scope-aimed shots dealing 120 damage (12 uncharged) to distant targets. Headshot deals 2.5x damage. 0.75 seconds to fully charge and 0.33 seconds to scope in/out. ";
        widowmaker.heroSpeed = "5.5 meters per second";
        widowmaker.heroPassiveName = "None";
        widowmaker.heroPassive = "";
        widowmaker.heroAbility1Name = "Grappling Hook";
        widowmaker.heroAbility1 = "Widowmaker launches a grappling hook at 20 m/s towards the location she’s aiming at with a 20 meter range – when the hook connects with a scalable surface, she’s quickly drawn towards it at 16 m/s, allowing her to expand her view of the battlefield and evade or flank targets. 12 second cooldown.";
        widowmaker.heroAbility2Name = "Venom Mine";
        widowmaker.heroAbility2 = "Widowmaker adheres a swiftly-arming venom mine to nearly any surface. When a target wanders within 3 meters of the mine’s motion trigger, it explodes, delivering poison gas to all enemies dealing 15 damage per second for 5 seconds. 15 second cooldown. 19 m/s projectile speed. ";
        widowmaker.heroUltimateName = "Infra-Sight";
        widowmaker.heroUltimate = "Widowmaker’s recon visor allows her to see the heat signatures of her targets through walls and objects for 15.5 seconds. This enhanced vision is shared with her allies. 0.5 second cast.";
        widowmaker.heroTipsAndTricks = "Stay in the back and kill priority targets. Grappling Hook can also be used on the ground to move faster.";
        widowmaker.heroClass = "damage";
        widowmaker.heroImage = R.drawable.widowmaker_smallerportrait;
        heroes.add(widowmaker);

        Hero winston = new Hero();
        winston.heroName = "Winston";
        winston.heroDifficulty = 2;
        winston.heroStrengths = "Great pusher";
        winston.heroWeaknesses = "Weak at long range";
        winston.heroHealth = 400;
        winston.heroArmor = 100;
        winston.heroShield = 0;
        winston.heroLeftClickDamage = "Winston’s weapon fires an electric barrage 8 meters forward dealing 60 damage per second to enemies in a 6 meter radius. 100 rounds. 20 rounds per second. 1.5 second reload. ";
        winston.heroRightClickDamage = "NA";
        winston.heroSpeed = "5.5 meters per second";
        winston.heroPassiveName = "None";
        winston.heroPassive = "";
        winston.heroAbility1Name = "Jump Pack";
        winston.heroAbility1 = "Assisted by his energy pack, Winston lunges up to 20 meters through the air, dealing 44 damage and staggering enemies within 5 meters where he lands. 6 second cooldown (2 during Primal Rage).";
        winston.heroAbility2Name = "Barrier Projector";
        winston.heroAbility2 = "Winston’s barrier projector extends a bubble-shaped field in a 5 meter radius for 6 seconds that absorbs 600 damage until it's destroyed. 13 second cooldown.";
        winston.heroUltimateName = "Primal Rage";
        winston.heroUltimate = "Winston embraces his animal nature, boosting his health to 900 and gaining 100 armor making him very difficult to kill, does 40 damage per swing that also knock back enemies in 4 meters, boosting movement speed to 7.1 m/s, and allowing him to use his Jump Pack ability more frequently. While raging, Winston can only make melee and Jump Pack attacks. Lasts 10 seconds.";
        winston.heroTipsAndTricks = "Use Primal Rage when low health. Try not to engage with Jump Pack. ";
        winston.heroClass = "tank";
        winston.heroImage = R.drawable.winston_smallerportrait;
        heroes.add(winston);

        Hero wrecking_ball = new Hero();
        wrecking_ball.heroName = "Wrecking Ball";
        wrecking_ball.heroDifficulty = 3;
        wrecking_ball.heroStrengths = "Large area damage";
        wrecking_ball.heroWeaknesses = "No long range damage";
        wrecking_ball.heroHealth = 500;
        wrecking_ball.heroArmor = 100;
        wrecking_ball.heroShield = 0;
        wrecking_ball.heroLeftClickDamage = "Wrecking Ball’s automatic assault cannons shoot 25 rounds per second dealing 5 damage each. 15 - 25 meter falloff. 80 rounds. 2.1 second reload.";
        wrecking_ball.heroRightClickDamage = "Wrecking Ball launches a grappling claw at 20 m/s, enabling him to anchor to an area and swing from it. If he strikes an enemy with a powered-up swing, they take 50 damage and are knocked back 10 meters.";
        wrecking_ball.heroSpeed = "5.5 meters per second";
        wrecking_ball.heroPassiveName = "Pile Driver";
        wrecking_ball.heroPassive = "Wrecking Ball slams onto the ground below, damaging enemies for 20 - 100 damage in an 8 meter radius and launching them upward. 10 second cooldown.";
        wrecking_ball.heroAbility1Name = "Roll";
        wrecking_ball.heroAbility1 = "Wrecking Ball transforms into a ball, increasing his movement speed to 10 m/s. Wrecking Ball has no critical hitbox while rolling.";
        wrecking_ball.heroAbility2Name = "Adaptive Shield";
        wrecking_ball.heroAbility2 = "Wrecking Ball gains a temporary shield for 7 seconds which protects him for 100 damage. Each opponent within 8 meters gives 100 more hp to his shield. 0.3 second cast. 15 second cooldown.";
        wrecking_ball.heroUltimateName = "Minefield";
        wrecking_ball.heroUltimate = "Wrecking Ball deploys a field of proximity mines which explode on contact with enemies dealing 130 damage in a 6 meter radius. Each mine has 50 Health and lasts for 20 seconds.";
        wrecking_ball.heroTipsAndTricks = "Reload while rolling and you will be harder to hit. Temporary shields do not provide enemies with ultimate charge.";
        wrecking_ball.heroClass = "tank";
        wrecking_ball.heroImage = R.drawable.wrecking_ball_smallerportrait;
        heroes.add(wrecking_ball);

        Hero zarya = new Hero();
        zarya.heroName = "Zarya";
        zarya.heroDifficulty = 3;
        zarya.heroStrengths = "Strong shields and can take a lot of damage";
        zarya.heroWeaknesses = "Low mobility";
        zarya.heroHealth = 200;
        zarya.heroArmor = 0;
        zarya.heroShield = 200;
        zarya.heroLeftClickDamage = "Zarya’s mighty Particle Cannon unleashes a 15 meter range beam of destructive energy that deals 95 - 190 damage per second. 100 rounds. 20 rounds per second. 1.6 second reload. ";
        zarya.heroRightClickDamage = "Zarya lobs an explosive charge to strike multiple opponents for 45 - 90 (23.5 - 47 self) damage in a 2 meter radius. 25 rounds per shot. 1 shot per second. 23.5 m/s projectile speed.";
        zarya.heroSpeed = "5.5 meters per second";
        zarya.heroPassiveName = "Energy";
        zarya.heroPassive = "+1 point of energy for every 5 damage blocked. Particle Cannon damage increases by 1% per point of charge (max of 100 energy). Energy decays 1.6% per second.  ";
        zarya.heroAbility1Name = "Particle Barrier";
        zarya.heroAbility1 = "The Particle Cannon can emit a personal barrier that gives Zarya 200 health against incoming attacks for 2 seconds, redirecting their energy to enhance her weapon’s damage and the width of its beam. 10 second cooldown.";
        zarya.heroAbility2Name = "Projected Barrier";
        zarya.heroAbility2 = "The Particle Cannon can emit a barrier that gives an ally within 30 meters 200 health against incoming attacks for 2 seconds, redirecting their energy to enhance her weapon’s damage and the width of its beam. 8 second cooldown.";
        zarya.heroUltimateName = "Graviton Surge";
        zarya.heroUltimate = "Zarya launches a gravity bomb that draws in enemy combatants within 6 meters and deals 5.5 damage per second over 4 seconds. 2 second delay. 25 m/s projectile speed.";
        zarya.heroTipsAndTricks = "Shield your allies and use your ultimate in combination with others.";
        zarya.heroClass = "tank";
        zarya.heroImage = R.drawable.zarya_smallerportrait;
        heroes.add(zarya);

        Hero zenyatta = new Hero();
        zenyatta.heroName = "Zenyatta";
        zenyatta.heroDifficulty = 3;
        zenyatta.heroStrengths = "Good damage and healing";
        zenyatta.heroWeaknesses = "Weak out in the open";
        zenyatta.heroHealth = 50;
        zenyatta.heroArmor = 0;
        zenyatta.heroShield = 100;
        zenyatta.heroLeftClickDamage = "Zenyatta projects his destructive energy orbs individually dealing 48 damage per orb. 2.5 shots per second. 20 rounds. 1.5 second reload. 80 m/s projectile speed.";
        zenyatta.heroRightClickDamage = "Zenyatta gathers his orbs charging 1 orb every .5 seconds for up to 5 orbs. He then projects each orb out every 0.1 seconds. ";
        zenyatta.heroSpeed = "5.5 meters per second";
        zenyatta.heroPassiveName = "None";
        zenyatta.heroPassive = "";
        zenyatta.heroAbility1Name = "Orb of Harmony";
        zenyatta.heroAbility1 = "Zenyatta casts an orb over the shoulder of a targeted ally within 40 meters. So long as Zenyatta maintains line of sight, the orb restores 30 health per second to his ally. Only one ally can receive the orb's benefit at a time. 3 second duration if line of sight is broken. 120 m/s projectile speed. 0 second cooldown.";
        zenyatta.heroAbility2Name = "Orb of Discord";
        zenyatta.heroAbility2 = "Attaching the orb of discord to an opponent amplifies the amount of damage they receive by 25% for as long as Zenyatta maintains line of sight. Only one opponent can suffer the orb's effects at a time. 3 second duration if line of sight is broken. 120 m/s projectile speed. 0 second cooldown.";
        zenyatta.heroUltimateName = "Transcendence";
        zenyatta.heroUltimate = "Zenyatta enters a state of heightened existence for 6 seconds. While transcendent, Zenyatta cannot use abilities or weapons, but is immune to damage and automatically restores his health and that of allies within 10 meters by 300 health per second. Zenyatta moves 11 m/s while using Transcendence.";
        zenyatta.heroTipsAndTricks = "Animation cancel using Orb of Discord. Melee to cancel your Orb Volley when no enemies are around.";
        zenyatta.heroClass = "support";
        zenyatta.heroImage = R.drawable.zenyatta_smallerportrait;
        heroes.add(zenyatta);

        return heroes;
    }

    public static List<Hero> getClassHeroes(String classType)
    {
        List<Hero> classTypeHeroes = new ArrayList<>();
        List<Hero> allHeroes = getAllHeroes();

        int numHeroes = allHeroes.size();

        for(int i = 0; i < numHeroes; i++)
        {
            if(allHeroes.get(i).heroClass.equals(classType))
            {
                addHeroToList(i, classTypeHeroes, allHeroes);
            }
        }
        return classTypeHeroes;
    }

    private static void addHeroToList(int i, List<Hero> heroList, List<Hero> allHeroes)
    {
        Hero hero = new Hero();
        hero.heroName = allHeroes.get(i).heroName;
        hero.heroDifficulty = allHeroes.get(i).heroDifficulty;
        hero.heroStrengths = allHeroes.get(i).heroStrengths;
        hero.heroWeaknesses = allHeroes.get(i).heroWeaknesses;
        hero.heroHealth = allHeroes.get(i).heroHealth;
        hero.heroArmor = allHeroes.get(i).heroArmor;
        hero.heroShield = allHeroes.get(i).heroShield;
        hero.heroLeftClickDamage = allHeroes.get(i).heroLeftClickDamage;
        hero.heroRightClickDamage = allHeroes.get(i).heroRightClickDamage;
        hero.heroSpeed = allHeroes.get(i).heroSpeed;
        hero.heroPassiveName = allHeroes.get(i).heroPassiveName;
        hero.heroPassive = allHeroes.get(i).heroPassive;
        hero.heroAbility1Name = allHeroes.get(i).heroAbility1Name;
        hero.heroAbility1 = allHeroes.get(i).heroAbility1;
        hero.heroAbility2Name = allHeroes.get(i).heroAbility2Name;
        hero.heroAbility2 = allHeroes.get(i).heroAbility2;
        hero.heroUltimateName = allHeroes.get(i).heroUltimateName;
        hero.heroUltimate = allHeroes.get(i).heroUltimate;
        hero.heroTipsAndTricks = allHeroes.get(i).heroTipsAndTricks;
        hero.heroClass = allHeroes.get(i).heroClass;
        hero.heroImage = allHeroes.get(i).heroImage;

        heroList.add(hero);
    }
}
